// <auto-generated />
using System;
using Fachep.EduMgr.Database;
using Fachep.EduMgr.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Fachep.EduMgr.Database.Migrations
{
    [DbContext(typeof(EduMgrContext))]
    [Migration("20260609093019_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "user", "admin", "teacher", "student" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fachep.EduMgr.Entities.Class", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("MajorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Config", b =>
                {
                    b.Property<bool>("Id")
                        .HasColumnType("boolean");

                    b.Property<string>("Sections")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("StartDayOfWeek")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Config");

                    b.HasData(
                        new
                        {
                            Id = true,
                            Sections = "[{\"StartTime\":\"08:10:00\",\"EndTime\":\"08:55:00\"},{\"StartTime\":\"09:05:00\",\"EndTime\":\"09:50:00\"},{\"StartTime\":\"10:10:00\",\"EndTime\":\"10:55:00\"},{\"StartTime\":\"11:05:00\",\"EndTime\":\"11:50:00\"},{\"StartTime\":\"14:40:00\",\"EndTime\":\"15:25:00\"},{\"StartTime\":\"15:35:00\",\"EndTime\":\"16:20:00\"},{\"StartTime\":\"16:30:00\",\"EndTime\":\"17:15:00\"},{\"StartTime\":\"17:25:00\",\"EndTime\":\"18:10:00\"},{\"StartTime\":\"19:30:00\",\"EndTime\":\"20:15:00\"},{\"StartTime\":\"20:25:00\",\"EndTime\":\"21:10:00\"},{\"StartTime\":\"12:30:00\",\"EndTime\":\"13:15:00\"},{\"StartTime\":\"13:25:00\",\"EndTime\":\"14:10:00\"}]",
                            StartDate = new DateOnly(2026, 9, 1),
                            StartDayOfWeek = 1
                        });
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Enrollment", b =>
                {
                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("OwnerId", "CourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Enrollment");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Major", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Major");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<NpgsqlRange<int>[]>("Days")
                        .IsRequired()
                        .HasColumnType("int4multirange");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<NpgsqlRange<int>[]>("Sections")
                        .IsRequired()
                        .HasColumnType("int4multirange");

                    b.PrimitiveCollection<NpgsqlRange<int>[]>("Weeks")
                        .IsRequired()
                        .HasColumnType("int4multirange");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Subject", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<UserRole>("UserRole")
                        .HasColumnType("user_role");

                    b.HasKey("Id");

                    b.HasIndex("UserRole");

                    b.ToTable("User");

                    b.HasDiscriminator<UserRole>("UserRole").IsComplete(true).HasValue(UserRole.User);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.UserToken", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<Instant>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Value")
                        .HasColumnType("uuid");

                    b.HasKey("DeviceId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Admin", b =>
                {
                    b.HasBaseType("Fachep.EduMgr.Entities.User");

                    b.HasDiscriminator().HasValue(UserRole.Admin);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "管理员",
                            NormalizedName = "管理员",
                            PasswordHash = "AQAAAAIAAYagAAAAEAP2Ovb3bO7RxNeAD67N0Q5/FiGNXOHxA25gWhORnntKt9Oznr4AuI7gcAcLao7IQQ==",
                            SecurityStamp = "bdf61e19-9203-408e-bfc5-8aa677c32cd1",
                            UserRole = UserRole.Admin
                        });
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Student", b =>
                {
                    b.HasBaseType("Fachep.EduMgr.Entities.User");

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasDiscriminator().HasValue(UserRole.Student);
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Teacher", b =>
                {
                    b.HasBaseType("Fachep.EduMgr.Entities.User");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.HasIndex("DepartmentId");

                    b.HasDiscriminator().HasValue(UserRole.Teacher);
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Class", b =>
                {
                    b.HasOne("Fachep.EduMgr.Entities.Major", "Major")
                        .WithMany("Classes")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fachep.EduMgr.Entities.Teacher", "Owner")
                        .WithMany("Classes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Major");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Course", b =>
                {
                    b.HasOne("Fachep.EduMgr.Entities.Teacher", "Owner")
                        .WithMany("Courses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fachep.EduMgr.Entities.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Enrollment", b =>
                {
                    b.HasOne("Fachep.EduMgr.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fachep.EduMgr.Entities.Student", "Owner")
                        .WithMany("Enrollments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fachep.EduMgr.Entities.Subject", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Course");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Major", b =>
                {
                    b.HasOne("Fachep.EduMgr.Entities.Department", "Owner")
                        .WithMany("Majors")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Schedule", b =>
                {
                    b.HasOne("Fachep.EduMgr.Entities.Course", "Owner")
                        .WithMany("Schedules")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Subject", b =>
                {
                    b.HasOne("Fachep.EduMgr.Entities.Department", "Owner")
                        .WithMany("Subjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.UserToken", b =>
                {
                    b.HasOne("Fachep.EduMgr.Entities.User", "Owner")
                        .WithMany("Tokens")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Student", b =>
                {
                    b.HasOne("Fachep.EduMgr.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fachep.EduMgr.Entities.Subject", null)
                        .WithMany("Students")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Teacher", b =>
                {
                    b.HasOne("Fachep.EduMgr.Entities.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Department", b =>
                {
                    b.Navigation("Majors");

                    b.Navigation("Subjects");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Major", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Subject", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Enrollments");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.User", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Fachep.EduMgr.Entities.Teacher", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
