/**
 * Fachep.EduMgr.WebHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DayOfWeek } from '../models/DayOfWeek';
import { SectionInfo } from '../models/SectionInfo';
import { HttpFile } from '../http/http';

export class ConfigDto {
    'startDate': string;
    'startDayOfWeek': DayOfWeek;
    'sections': Array<SectionInfo>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string",
            "format": "date"
        },
        {
            "name": "startDayOfWeek",
            "baseName": "startDayOfWeek",
            "type": "DayOfWeek",
            "format": ""
        },
        {
            "name": "sections",
            "baseName": "sections",
            "type": "Array<SectionInfo>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConfigDto.attributeTypeMap;
    }

    public constructor() {
    }
}


