/**
 * Fachep.EduMgr.WebHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CourseDto {
    'id': number;
    'teacherId'?: number | null;
    'subjectId': number;
    'locked': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "teacherId",
            "baseName": "teacherId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "subjectId",
            "baseName": "subjectId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "locked",
            "baseName": "locked",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CourseDto.attributeTypeMap;
    }

    public constructor() {
    }
}
