/**
 * Fachep.EduMgr.WebHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EnrollmentDto {
    'locked': boolean;
    'studentId': number;
    'courseId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "locked",
            "baseName": "locked",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "studentId",
            "baseName": "studentId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "courseId",
            "baseName": "courseId",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return EnrollmentDto.attributeTypeMap;
    }

    public constructor() {
    }
}
