/**
 * Fachep.EduMgr.WebHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ScheduleDto {
    'id'?: string;
    'courseId': number;
    'location'?: string | null;
    'weeks': Array<Array<number>>;
    'days': Array<Array<number>>;
    'sections': Array<Array<number>>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "courseId",
            "baseName": "courseId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "weeks",
            "baseName": "weeks",
            "type": "Array<Array<number>>",
            "format": "int32"
        },
        {
            "name": "days",
            "baseName": "days",
            "type": "Array<Array<number>>",
            "format": "int32"
        },
        {
            "name": "sections",
            "baseName": "sections",
            "type": "Array<Array<number>>",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return ScheduleDto.attributeTypeMap;
    }

    public constructor() {
    }
}
