/**
 * Fachep.EduMgr.WebHost
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserRole } from '../models/UserRole';
import { HttpFile } from '../http/http';

export class UserDto {
    'name'?: string | null;
    'email'?: string | null;
    'id': number;
    'userRole': UserRole;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "userRole",
            "baseName": "userRole",
            "type": "UserRole",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserDto.attributeTypeMap;
    }

    public constructor() {
    }
}


